services:
  mirakurun:
    build: .
    environment:
      TZ: Asia/Tokyo
      # set to "1" to disable pcscd
      # pcscd を無効にする場合は "1"
      DISABLE_PCSCD: "0"
      # set to "1" to disable fetch/build the B25 test decoder command
      # B25 テストコマンドの取得とビルドを無効にする場合は "1"
      DISABLE_B25_TEST: "0"
      # comment out below if you commented out `network_mode: host`
      # `network_mode: host` をコメントアウトする場合はここもコメントアウト
      DOCKER_NETWORK: host
      # set hostname if accesing by hostname (other than IP address)
      # ブラウザから IP アドレス以外でアクセスする場合はホスト名を設定
      hostname: mirakurun
      # for debug
      #LOG_LEVEL: "3"
      #DEBUG: "true"
    devices:
      # if you use card readers
      # カードリーダーを使う場合
      - /dev/bus:/dev/bus
      # if use DVB devices
      # DVB チューナーを使う場合
      - /dev/pt3video0:/dev/pt3video0
      - /dev/pt3video1:/dev/pt3video1
      - /dev/pt3video2:/dev/pt3video2
      - /dev/pt3video3:/dev/pt3video3

    volumes:
      # you can change to any location if you want.
      - /opt/mirakurun/run:/var/run
      - /opt/mirakurun/opt:/opt
      - ./config:/app-config
      - /opt/mirakurun/data:/app-data

      # if use host's pcscd (DISABLE_PCSCD=1)
      # ホストの pcscd を使う場合 (DISABLE_PCSCD=1)
      #- /var/run/pcscd/pcscd.comm:/var/run/pcscd/pcscd.comm

      # add all devices (for development purposes)
      # 全てのデバイスを追加 (開発用)
      #- /dev:/dev

    container_name: mirakurun
    privileged: true
    network_mode: host
    cap_add:
      - SYS_ADMIN
      - SYS_NICE
    device_cgroup_rules:
      - 'c *:* rmw'
    tmpfs:
      - /tmp
    restart: always
    logging:
      driver: json-file
      options:
        max-file: "1"
        max-size: 10m
